-- MySQL Script generated by MySQL Workbench
-- Sat Jul 16 10:45:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema decoraci_decopino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema decoraci_decopino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `decoraci_decopino` DEFAULT CHARACTER SET utf8 ;
USE `decoraci_decopino` ;

-- -----------------------------------------------------
-- Table `decoraci_decopino`.`madpaises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`madpaises` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `pais` VARCHAR(100) NULL COMMENT 'Nombre del pais que se registra',
  `estado` INT NULL COMMENT '0 inactivo\n1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de registro del pais',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al nombre del pais',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`departamentos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `departamento` VARCHAR(100) NULL COMMENT 'Nombre del departamento que se registra',
  `pais` INT NOT NULL COMMENT 'Identificador del pais al que pertenece el departamento',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NOT NULL COMMENT 'Fecha de registro del departamento',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo de departamento',
  PRIMARY KEY (`id`),
  INDEX `fk_departamentos_paises1_idx` (`pais` ASC),
  CONSTRAINT `fk_departamentos_paises1`
    FOREIGN KEY (`pais`)
    REFERENCES `decoraci_decopino`.`madpaises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`madciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`madciudades` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador unico del registro',
  `ciudad` VARCHAR(100) NOT NULL COMMENT 'Nombre de la ciudad registrada',
  `departamento` INT NOT NULL COMMENT 'Identificador del departamento al que pertenece la ciudad',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NOT NULL COMMENT ' Fecha de registro de la ciudad',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo de ciudad',
  PRIMARY KEY (`id`),
  INDEX `fk_ciudades_departamentos1_idx` (`departamento` ASC),
  CONSTRAINT `fk_ciudades_departamentos1`
    FOREIGN KEY (`departamento`)
    REFERENCES `decoraci_decopino`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`madpersonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`madpersonas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `tidentificacion` VARCHAR(45) NULL COMMENT 'Tipo de identificación de la persona',
  `identificacion` INT NULL COMMENT 'Número de identificación de la persona',
  `nombre` VARCHAR(45) NULL COMMENT 'Nombre de la persona que se registra ',
  `apellido` VARCHAR(45) NULL COMMENT 'Apellido de la persona que se registra ',
  `correo` VARCHAR(45) NULL COMMENT 'Correo de la persona que se registra ',
  `telefono` VARCHAR(45) NULL COMMENT 'Telefono de la persona que se registra ',
  `direccion` VARCHAR(100) NULL COMMENT 'Dirección de la persona que se registra ',
  `ciudad` INT NOT NULL COMMENT 'Identificador de la ciudad al que resida la persona',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de registro de la persona',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación a los campos tidentificación, nombre, apellido, correo, telefono, dirección o ciudad.\n',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC),
  INDEX `fk_personas_ciudades1_idx` (`ciudad` ASC),
  CONSTRAINT `fk_personas_ciudades1`
    FOREIGN KEY (`ciudad`)
    REFERENCES `decoraci_decopino`.`madciudades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mprproveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mprproveedores` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `persona` INT NOT NULL COMMENT 'Identificador de los datos de la tabla persona relacionada a el proveedor',
  `fregistro` VARCHAR(25) NOT NULL COMMENT 'Fecha de registro del proveedor',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo de estado',
  PRIMARY KEY (`id`),
  INDEX `fk_PROVEEDORES_Personas1_idx` (`persona` ASC),
  CONSTRAINT `fk_PROVEEDORES_Personas1`
    FOREIGN KEY (`persona`)
    REFERENCES `decoraci_decopino`.`madpersonas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mprcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mprcategorias` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro\n',
  `nombre` VARCHAR(45) NULL COMMENT 'Nombre de la categoria que se registra',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de registro de la categoria',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo nombre\n',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mprsucategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mprsucategorias` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `nombre` VARCHAR(45) NOT NULL COMMENT 'Nombre de la subcategoria que se registra ',
  `categoria` INT NOT NULL COMMENT 'Identificador de la categoria a la que pertenece la subcategoria',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NOT NULL COMMENT 'Fecha de registro de la subcategoria',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo nombre',
  PRIMARY KEY (`id`),
  INDEX `fk_subcategorias_categorias1_idx` (`categoria` ASC),
  CONSTRAINT `fk_subcategorias_categorias1`
    FOREIGN KEY (`categoria`)
    REFERENCES `decoraci_decopino`.`mprcategorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mprlineas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mprlineas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `nombre` VARCHAR(45) NOT NULL COMMENT 'Nombre del tipo de linea que se registra (juvenil, infantil, ) ',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de registro de la linea',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo nombre',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mprproductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mprproductos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `nombre` VARCHAR(45) NOT NULL COMMENT 'Nombre del producto que se registra ',
  `precio` INT NOT NULL COMMENT 'Valor de la unidad del producto que se registra ',
  `iva` INT NULL COMMENT 'Valor del iva del producto que se registra ',
  `descuento` INT NULL COMMENT 'Valor del descuento del producto que se registra ',
  `existencia` INT NULL COMMENT 'Número de unidades del producto en el inventario',
  `estilo` VARCHAR(45) NULL COMMENT 'Estilo del producto que se registra ',
  `dimension` VARCHAR(45) NOT NULL COMMENT 'Medidas del producto que se registra ',
  `peso` VARCHAR(45) NOT NULL COMMENT 'Peso del producto que se registra ',
  `material` VARCHAR(45) NOT NULL COMMENT 'Material con el que esta hecho el producto que se registra ',
  `color` VARCHAR(45) NULL COMMENT 'Color general del producto\n',
  `tipopintura` VARCHAR(45) NULL COMMENT 'poliuretano o colores naturales\n',
  `Acabado` VARCHAR(10) NULL COMMENT 'brillante, semi mate o mate',
  `imagen` VARCHAR(255) NOT NULL COMMENT 'Ruta de almacenamiento de la imagen del producto',
  `detalle` VARCHAR(1000) NOT NULL COMMENT 'Detalles del producto que se registra ',
  `vista` INT NOT NULL COMMENT 'Numero de vistas que tenga el producto',
  `compra` INT NOT NULL COMMENT 'Numero de veces que fue comprado el producto',
  `garantia` VARCHAR(45) NULL COMMENT 'Tiempo de garantia del producto',
  `Proveedor` INT NULL COMMENT 'Identificador del proveedro que proporciona este producto',
  `linea` INT NULL COMMENT 'Identificador de la linea a la que pertenece el producto',
  `categoria` INT NOT NULL COMMENT 'Identificador de la categoria a la que pertenece el producto',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NOT NULL COMMENT 'Fecha de registro del producto',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo nombre, valor, material, iva, descuanto, existencia, estilo, dimension, peso, imagen, vistas, compras o proveedor\n',
  PRIMARY KEY (`id`),
  INDEX `fk_producto_proveedor1_idx` (`Proveedor` ASC),
  INDEX `fk_productos_categorias1_idx` (`categoria` ASC),
  INDEX `fk_mprproductos_mprlineas1_idx` (`linea` ASC),
  CONSTRAINT `fk_producto_proveedor1`
    FOREIGN KEY (`Proveedor`)
    REFERENCES `decoraci_decopino`.`mprproveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_categorias1`
    FOREIGN KEY (`categoria`)
    REFERENCES `decoraci_decopino`.`mprsucategorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mprproductos_mprlineas1`
    FOREIGN KEY (`linea`)
    REFERENCES `decoraci_decopino`.`mprlineas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mususuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mususuarios` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `login` VARCHAR(45) NOT NULL COMMENT 'Nombre para identificar el usuario que se registra ',
  `contrasenia` VARCHAR(255) NOT NULL COMMENT 'Contraseña del usuario que se registra ',
  `fotoperfil` VARCHAR(255) NULL COMMENT 'Ruta de almacenamiento de la imagen del usuario',
  `persona` INT NOT NULL COMMENT 'Identificador de los datos de la tabla persona relacionada a el usuario',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NOT NULL COMMENT 'Fecha de registro del usuario',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo de login, contrasenia o persona',
  PRIMARY KEY (`id`),
  INDEX `fk_Usuario_Personas1_idx` (`persona` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_Usuario_Personas1`
    FOREIGN KEY (`persona`)
    REFERENCES `decoraci_decopino`.`madpersonas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mclclientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mclclientes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `login` VARCHAR(45) NOT NULL COMMENT 'Nombre identificador del cliente',
  `contrasenia` VARCHAR(255) NOT NULL COMMENT 'Contraseña del cliente que se registra ',
  `fotoperfil` VARCHAR(255) NULL COMMENT 'Ruta de almacenamiento de la imagen del cliente',
  `persona` INT NOT NULL COMMENT 'Identificador de los datos de la tabla persona relacionada a el cliente',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de registro del cliente',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo login o contrasenia',
  PRIMARY KEY (`id`),
  INDEX `fk_clientes_muspersonas1_idx` (`persona` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_clientes_muspersonas1`
    FOREIGN KEY (`persona`)
    REFERENCES `decoraci_decopino`.`madpersonas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mprtparticulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mprtparticulos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `nombre` VARCHAR(45) NOT NULL COMMENT 'Nombre del tipo de articulo que se registra',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de registro del tipo de articulo',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo nombre',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mprmarcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mprmarcas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `nombre` VARCHAR(45) NULL COMMENT 'Nombre de la marca que se registra ',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de registro de la marca',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo nombre\n',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mprarticulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mprarticulos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `nombre` VARCHAR(45) NOT NULL COMMENT 'Nombre de la decoracion que se registra ',
  `descripcion` VARCHAR(500) NULL COMMENT 'Decripción de la decoración que se registra ',
  `imagen` VARCHAR(255) NOT NULL COMMENT 'Ruta de almacenamiento de la imagen de la decoración',
  `precio` INT NOT NULL COMMENT 'Nombre de la decoración que se registra \n',
  `existencia` INT NULL COMMENT 'Número de unidades del producto en el inventario',
  `marca` INT NULL COMMENT 'Identificador de la marca que tiene el articulo',
  `tipoarticulo` INT NOT NULL COMMENT 'Identificador del tipo de articulo al que pertenece el articulo',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de registro de la decoración',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al titulo, descripción, imagen o precio',
  PRIMARY KEY (`id`),
  INDEX `fk_mprarticulos_mprtparticulos1_idx` (`tipoarticulo` ASC),
  INDEX `fk_mprarticulos_mprmarcas1_idx` (`marca` ASC),
  CONSTRAINT `fk_mprarticulos_mprtparticulos1`
    FOREIGN KEY (`tipoarticulo`)
    REFERENCES `decoraci_decopino`.`mprtparticulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mprarticulos_mprmarcas1`
    FOREIGN KEY (`marca`)
    REFERENCES `decoraci_decopino`.`mprmarcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mprcombos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mprcombos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `nombre` VARCHAR(45) NOT NULL COMMENT 'Nombre del combo que se registra ',
  `vistas` INT NULL COMMENT 'Numero de vistas que tiene el combo',
  `compras` INT NULL COMMENT 'Numero de compras que tenga el producto',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NOT NULL COMMENT 'Fecha de creación del combo',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación el campo vistas, nombre o compras',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`madcomentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`madcomentarios` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `comentario` VARCHAR(500) NOT NULL COMMENT 'Contenido del comentario',
  `clientes` INT NOT NULL COMMENT 'Identificador del cliente que realiza el comentario',
  `producto` INT NULL COMMENT 'Identificador del producto al que pertenece el comentario',
  `articulo` INT NULL COMMENT 'Identificador del articulo al que pertenece el comentario',
  `combo` INT NULL COMMENT 'Identificador del combo al que pertenece el comentario',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NOT NULL COMMENT 'Fecha de registro del comentario',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo de comentario',
  PRIMARY KEY (`id`),
  INDEX `fk_COMENTARIO_PRODUCTO1_idx` (`producto` ASC),
  INDEX `fk_comentarios_clientes1_idx` (`clientes` ASC),
  INDEX `fk_madcomentarios_mprarticulos1_idx` (`articulo` ASC),
  INDEX `fk_madcomentarios_mprcombos1_idx` (`combo` ASC),
  CONSTRAINT `fk_COMENTARIO_PRODUCTO1`
    FOREIGN KEY (`producto`)
    REFERENCES `decoraci_decopino`.`mprproductos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_clientes1`
    FOREIGN KEY (`clientes`)
    REFERENCES `decoraci_decopino`.`mclclientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_madcomentarios_mprarticulos1`
    FOREIGN KEY (`articulo`)
    REFERENCES `decoraci_decopino`.`mprarticulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_madcomentarios_mprcombos1`
    FOREIGN KEY (`combo`)
    REFERENCES `decoraci_decopino`.`mprcombos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mvecarritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mvecarritos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro\n',
  `cliente` INT NOT NULL COMMENT 'Identificador del cliente al que pertenece el carrito',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NOT NULL COMMENT 'Fecha de creacion del carriro',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha de inhabilitación del carrito',
  PRIMARY KEY (`id`),
  INDEX `fk_carritos_clientes1_idx` (`cliente` ASC),
  CONSTRAINT `fk_carritos_clientes1`
    FOREIGN KEY (`cliente`)
    REFERENCES `decoraci_decopino`.`mclclientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mvefacturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mvefacturas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `total` INT NULL COMMENT 'Valor total de la factura',
  `cliente` INT NOT NULL,
  `estadoenvio` VARCHAR(45) NOT NULL COMMENT '0 en proceso, 1 enviado, 2 cancelado   ',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NOT NULL COMMENT 'Fecha de registro de la factura',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación a la factura',
  PRIMARY KEY (`id`),
  INDEX `fk_facturas_clientes1_idx` (`cliente` ASC),
  CONSTRAINT `fk_facturas_clientes1`
    FOREIGN KEY (`cliente`)
    REFERENCES `decoraci_decopino`.`mclclientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mvedetfacturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mvedetfacturas` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `subtotal` INT NOT NULL COMMENT 'Subtotal del producto o combo',
  `iva` INT NOT NULL COMMENT 'Valor del iva del producto o combo',
  `descuento` INT NOT NULL COMMENT 'Descuento del producto o combo',
  `detalles` VARCHAR(5000) NOT NULL COMMENT 'Detalle de compra',
  `cantidad` INT NOT NULL COMMENT 'numero de unidades de los productos o productos',
  `metodopago` VARCHAR(45) NOT NULL COMMENT 'Metodo de pago',
  `preciounidad` INT NULL COMMENT 'Precio de la unidad ',
  `carrito` INT NOT NULL COMMENT 'Identificador del carrito al que pertenece los detalles de la factura',
  `factura` INT NOT NULL COMMENT 'Identificador de la factura al que pertenece los detalles de la factura',
  `combo` INT NULL COMMENT 'Identificador del combo que se va facturar',
  `producto` INT NULL COMMENT 'Identificador del producto que se va facturar',
  `articulo` INT NULL COMMENT 'Identificador del articulo que se va facturar',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NOT NULL COMMENT 'Fecha de realización de factura',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación de la factura',
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_factura_producto_carrito1_idx` (`carrito` ASC),
  INDEX `fk_DETALLE_FACTURAS_FACTURAS1_idx` (`factura` ASC),
  INDEX `fk_DETALLE_FACTURAS_PRODUCTOS1_idx` (`producto` ASC),
  INDEX `fk_detalle_facturas_combos1_idx` (`combo` ASC),
  INDEX `fk_mvedetfacturas_mprarticulos1_idx` (`articulo` ASC),
  CONSTRAINT `fk_detalle_factura_producto_carrito1`
    FOREIGN KEY (`carrito`)
    REFERENCES `decoraci_decopino`.`mvecarritos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_FACTURAS_FACTURAS1`
    FOREIGN KEY (`factura`)
    REFERENCES `decoraci_decopino`.`mvefacturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLE_FACTURAS_PRODUCTOS1`
    FOREIGN KEY (`producto`)
    REFERENCES `decoraci_decopino`.`mprproductos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_facturas_combos1`
    FOREIGN KEY (`combo`)
    REFERENCES `decoraci_decopino`.`mprcombos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mvedetfacturas_mprarticulos1`
    FOREIGN KEY (`articulo`)
    REFERENCES `decoraci_decopino`.`mprarticulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mcllistadeseos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mcllistadeseos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `cliente` INT NOT NULL COMMENT 'Identificador del cliente al que pertenece la lista de deseos\n',
  `combo` INT NULL,
  `articulo` INT NULL,
  `Producto` INT NULL COMMENT 'Identificador del producto agregado a la lista de deseos',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo\n',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de registro de producto o combo en la lista de deseos',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo estado',
  PRIMARY KEY (`id`),
  INDEX `fk_lista_deseos_producto1_idx` (`Producto` ASC),
  INDEX `fk_lista_deseos_clientes1_idx` (`cliente` ASC),
  INDEX `fk_mcllistadeseos_mprcombos1_idx` (`combo` ASC),
  INDEX `fk_mcllistadeseos_mprarticulos1_idx` (`articulo` ASC),
  CONSTRAINT `fk_lista_deseos_producto1`
    FOREIGN KEY (`Producto`)
    REFERENCES `decoraci_decopino`.`mprproductos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lista_deseos_clientes1`
    FOREIGN KEY (`cliente`)
    REFERENCES `decoraci_decopino`.`mclclientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mcllistadeseos_mprcombos1`
    FOREIGN KEY (`combo`)
    REFERENCES `decoraci_decopino`.`mprcombos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mcllistadeseos_mprarticulos1`
    FOREIGN KEY (`articulo`)
    REFERENCES `decoraci_decopino`.`mprarticulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`madsesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`madsesion` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `plataforma` VARCHAR(45) NULL COMMENT 'Indica en que plataforma se realizó el inicio de sesión',
  `usuario` INT NULL COMMENT 'Identificador del usuario que inicia sesión',
  `cliente` INT NULL COMMENT 'Identificador del cliente que inicia sesión',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NOT NULL COMMENT 'Fecha en que se realizó el inicio de sesión',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se cerro la sesión',
  PRIMARY KEY (`id`),
  INDEX `fk_LOGS_USUARIO1_idx` (`usuario` ASC),
  INDEX `fk_logs_clientes1_idx` (`cliente` ASC),
  CONSTRAINT `fk_LOGS_USUARIO1`
    FOREIGN KEY (`usuario`)
    REFERENCES `decoraci_decopino`.`mususuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logs_clientes1`
    FOREIGN KEY (`cliente`)
    REFERENCES `decoraci_decopino`.`mclclientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`madroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`madroles` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `nombre` VARCHAR(45) NOT NULL COMMENT 'Nombre del rol que se registra ',
  `codigo` VARCHAR(10) NULL COMMENT 'Codigo del rol que se registra ',
  `funciones` VARCHAR(200) NULL COMMENT 'Funciones del rol que se registra ',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistrado` VARCHAR(25) NOT NULL COMMENT 'Fecha de registro del rol',
  `factualizaco` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación los campos nombre, codigo, funciones o estado. ',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nomRol_UNIQUE` (`nombre` ASC),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mprcomproductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mprcomproductos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '\nIdentificador único del registro\n',
  `total` INT NULL COMMENT 'V\'alor total del combo',
  `descuento` VARCHAR(45) NULL COMMENT 'Descuento del combo',
  `Combo` INT NOT NULL COMMENT 'Identificador del combo al que pertenece la lista de producto',
  `producto` INT NOT NULL COMMENT 'Identificador de los productos que pertenece al combo',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de registro del combo',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo total o descuento',
  INDEX `fk_Combos_has_PRODUCTOS_Combos1_idx` (`Combo` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_COMBOS_PRODUCTOS_PRODUCTOS1_idx` (`producto` ASC),
  CONSTRAINT `fk_Combos_has_PRODUCTOS_Combos1`
    FOREIGN KEY (`Combo`)
    REFERENCES `decoraci_decopino`.`mprcombos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMBOS_PRODUCTOS_PRODUCTOS1`
    FOREIGN KEY (`producto`)
    REFERENCES `decoraci_decopino`.`mprproductos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mvedetcarritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mvedetcarritos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `cantidad` INT NULL COMMENT 'Cantidad de unidades del producto o combo',
  `combo` INT NULL COMMENT 'Identificador del combo agregado al carrito',
  `producto` INT NULL COMMENT 'Identificador del producto agregado al carrito',
  `articulo` INT NULL COMMENT 'Identificador del articulo agregado al carrito',
  `carrito` INT NOT NULL COMMENT 'Identificador del carrito al que corresponden los detalles de los productos o combos agregados al carrito',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha en que se agrega un producto o combo al carrito',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación en la cantidad de productos o combos',
  PRIMARY KEY (`id`),
  INDEX `fk_Detalle_carritos_Combos1_idx` (`combo` ASC),
  INDEX `fk_Detalle_carritos_PRODUCTOS1_idx` (`producto` ASC),
  INDEX `fk_Detalle_carritos_CARRITOS1_idx` (`carrito` ASC),
  INDEX `fk_mvedetcarritos_mprarticulos1_idx` (`articulo` ASC),
  CONSTRAINT `fk_Detalle_carritos_Combos1`
    FOREIGN KEY (`combo`)
    REFERENCES `decoraci_decopino`.`mprcombos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_carritos_PRODUCTOS1`
    FOREIGN KEY (`producto`)
    REFERENCES `decoraci_decopino`.`mprproductos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_carritos_CARRITOS1`
    FOREIGN KEY (`carrito`)
    REFERENCES `decoraci_decopino`.`mvecarritos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mvedetcarritos_mprarticulos1`
    FOREIGN KEY (`articulo`)
    REFERENCES `decoraci_decopino`.`mprarticulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`madusuarioroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`madusuarioroles` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `usuario` INT NOT NULL COMMENT 'Identificador del usuario al que se le asigna el rol',
  `rol` INT NOT NULL COMMENT 'Identificador del rol que se le otorga al usuario',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de asignacion del rol al usuario',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo estado',
  INDEX `fk_usuarios_has_roles_roles1_idx` (`rol` ASC),
  INDEX `fk_usuarios_has_roles_usuarios1_idx` (`usuario` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuarios_has_roles_usuarios1`
    FOREIGN KEY (`usuario`)
    REFERENCES `decoraci_decopino`.`mususuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_roles_roles1`
    FOREIGN KEY (`rol`)
    REFERENCES `decoraci_decopino`.`madroles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`madtiparametros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`madtiparametros` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `nombre` VARCHAR(45) NULL COMMENT 'Nombre del tipo de parametro que se registra',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de registro del tipo de parametro',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo nombre',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`madparametros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`madparametros` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `nombre` VARCHAR(45) NULL COMMENT 'Nombre del parametro que se registra ',
  `madparametroscol` VARCHAR(45) NULL,
  `estado` INT NULL,
  `tiparametro` INT NOT NULL COMMENT 'Identificador del tipo de parametro al que pertenece el parametro',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de registro de parametro',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo nombre',
  PRIMARY KEY (`id`),
  INDEX `fk_madparametros_madtiparametros1_idx` (`tiparametro` ASC),
  CONSTRAINT `fk_madparametros_madtiparametros1`
    FOREIGN KEY (`tiparametro`)
    REFERENCES `decoraci_decopino`.`madtiparametros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mprbanners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mprbanners` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `nombre` VARCHAR(45) NULL COMMENT 'Nombre del banner que se registra ',
  `imagen` VARCHAR(255) NOT NULL COMMENT 'Ruta de almacenamiento de la imagen del banner',
  `descripcion` VARCHAR(100) NULL COMMENT 'Descripción del banner que se registra',
  `producto` INT NULL COMMENT 'Identificador del producto al que está relacionado el banner',
  `combo` INT NULL,
  `fregistro` VARCHAR(25) NOT NULL COMMENT 'Fecha de registro del banner',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación al campo nombre o imagen',
  PRIMARY KEY (`id`),
  INDEX `fk_mprbanners_mprproductos1_idx` (`producto` ASC),
  INDEX `fk_mprbanners_mprcombos1_idx` (`combo` ASC),
  CONSTRAINT `fk_mprbanners_mprproductos1`
    FOREIGN KEY (`producto`)
    REFERENCES `decoraci_decopino`.`mprproductos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mprbanners_mprcombos1`
    FOREIGN KEY (`combo`)
    REFERENCES `decoraci_decopino`.`mprcombos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`mvecomprobantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`mvecomprobantes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único del registro',
  `archivo` VARCHAR(255) NULL COMMENT 'Ruta en la que almacenara el comprobante',
  `factura` INT NOT NULL COMMENT 'Identificador de la factura a la que pertenece el comprobante',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de creacion del comprobante',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se subio el comprobante',
  PRIMARY KEY (`id`),
  INDEX `fk_mvecomprobantes_mvefacturas1_idx` (`factura` ASC),
  CONSTRAINT `fk_mvecomprobantes_mvefacturas1`
    FOREIGN KEY (`factura`)
    REFERENCES `decoraci_decopino`.`mvefacturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`madrecursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`madrecursos` (
  `id` INT NOT NULL COMMENT 'Identificador único del registro',
  `codigo` VARCHAR(10) NULL COMMENT 'Codigo del recurso',
  `nombre` VARCHAR(45) NULL COMMENT 'Nombre del recurso',
  `descripcion` VARCHAR(200) NULL COMMENT 'Descripción del recurso',
  `ruta` VARCHAR(60) NULL COMMENT 'Ruta de almacenamiento del recurso',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de registro del recurso',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación los campos codigo, nombre, descripcion, ruta o estado.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decoraci_decopino`.`madrolrecursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decoraci_decopino`.`madrolrecursos` (
  `id` INT NOT NULL COMMENT 'Identificador único del registro',
  `recurso` INT NOT NULL COMMENT 'Identificador del recurso al que se le establecen los permisos para los roles',
  `rol` INT NOT NULL COMMENT 'Identificador del rol al que se le designan los permisos',
  `crear` INT NULL COMMENT 'Permiso para crear en el recurso',
  `leer` INT NULL COMMENT 'Permiso para ver el recurso',
  `editar` INT NULL COMMENT 'Permiso para editar en el recurso',
  `eliminar` INT NULL COMMENT 'Permiso para eliminar en el recurso',
  `estado` INT NULL COMMENT '0 inactivo, 1 activo',
  `fregistro` VARCHAR(25) NULL COMMENT 'Fecha de registro de los permisos que el rol tiene en el recurso',
  `factualizado` VARCHAR(25) NULL COMMENT 'Fecha en que se hizo una modificación a los permisos que el rol tiene en el recurso',
  INDEX `fk_madrecursos_has_madroles_madroles1_idx` (`rol` ASC),
  INDEX `fk_madrecursos_has_madroles_madrecursos1_idx` (`recurso` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_madrecursos_has_madroles_madrecursos1`
    FOREIGN KEY (`recurso`)
    REFERENCES `decoraci_decopino`.`madrecursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_madrecursos_has_madroles_madroles1`
    FOREIGN KEY (`rol`)
    REFERENCES `decoraci_decopino`.`madroles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
